### ISSUE TITLE
alpine-line with lein 2.8.1

### ISSUE THREAD

**Issue by mdaley** [naartjie/dockers#1]
Hi, with the release of lein 2.8.1 which fixes some bugs, it would be really cool if you could re-release the alpine-lein docker image.  It would really help with our CI processes! :-)

**Comment by naartjie** [comment]
@mdaley thanks for pinging me. I've just kicked off another buiild: https://hub.docker.com/r/naartjie/alpine-lein/builds/bmybyuw86xbzmpwvnkifyut/ which should solve it.

**Comment by naartjie** [comment]
@mdaley `latest` is on version `2.8.1`.

Thanks

**Comment by mdaley** [comment]
Nice, thanks very much!
